# Generated by Django 4.0 on 2021-12-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_image', models.ImageField(upload_to='slider')),
                ('meta', models.TextField(max_length=80)),
                ('title', models.TextField(max_length=256)),
                ('description', models.TextField(max_length=256)),
            ],
        ),
    ]
