# Generated by Django 4.0 on 2021-12-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='meta',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
