# Generated by Django 4.0 on 2021-12-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0004_course_feature_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='choice',
            field=models.IntegerField(choices=[(1, 'Popular'), (2, 'Rcent'), (3, 'Maxedu')], null=True),
        ),
    ]
