# Generated by Django 4.0 on 2021-12-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0005_course_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='choice',
        ),
        migrations.AddField(
            model_name='course',
            name='is_popular',
            field=models.IntegerField(choices=[(1, 'Yes')], null=True),
        ),
    ]
