# Generated by Django 4.0 on 2021-12-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0006_remove_course_choice_course_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('price', models.CharField(max_length=128)),
                ('duration', models.CharField(max_length=128)),
                ('feature_1', models.CharField(max_length=128)),
                ('feature_2', models.CharField(max_length=128)),
                ('feature_3', models.CharField(max_length=128)),
                ('feature_4', models.CharField(max_length=128)),
                ('feature_5', models.CharField(max_length=128)),
                ('feature_6', models.CharField(max_length=128)),
                ('feature_7', models.CharField(max_length=128)),
            ],
        ),
    ]
