# Generated by Django 4.0 on 2021-12-15 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0007_faq_pricing_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_popular',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], null=True),
        ),
    ]
