# Generated by Django 4.0 on 2021-12-15 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0009_course_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_added',
        ),
    ]
