# Generated by Django 4.0 on 2021-12-15 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0012_remove_pricing_table_feature_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing_table',
            old_name='title',
            new_name='sub_text',
        ),
    ]
