# Generated by Django 4.0 on 2021-12-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0013_rename_title_pricing_table_sub_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_popular',
        ),
        migrations.AddField(
            model_name='course',
            name='popular',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], null=True),
        ),
    ]
