# Generated by Django 4.0 on 2021-12-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0014_remove_course_is_popular_course_popular'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='feature_image',
            new_name='featured_image',
        ),
    ]
