# Generated by Django 4.0 on 2022-01-16 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0017_alter_pricing_table_options_curriculum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(max_length=300)),
                ('host_location', models.TextField(max_length=126)),
            ],
        ),
        migrations.CreateModel(
            name='Side_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': ('Side Description',),
                'verbose_name_plural': 'Side Descriptions',
            },
        ),
    ]
