# Generated by Django 4.0 on 2022-03-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0018_content_event_side_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Side_description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='short_description',
            new_name='short_note',
        ),
        migrations.AddField(
            model_name='event',
            name='event_description',
            field=models.TextField(null=True),
        ),
    ]
