# Generated by Django 4.0 on 2022-03-08 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0019_delete_side_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='host_location',
        ),
    ]
