# Generated by Django 4.0 on 2022-03-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0021_event_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_note', models.TextField(max_length=300)),
                ('event_description', models.TextField(null=True)),
                ('featured_image', models.ImageField(default='default.jpg', upload_to='events')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
