# Generated by Django 4.0 on 2022-03-08 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0022_events_delete_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
    ]
