# Generated by Django 4.0 on 2022-03-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0026_content_event_event_assesments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='short_note',
            field=models.TextField(max_length=500),
        ),
    ]
