# Generated by Django 4.0.3 on 2022-03-08 17:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0028_alter_event_short_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
