# Generated by Django 4.0.3 on 2022-03-08 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0032_comment_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Speech',
        ),
        migrations.AlterModelOptions(
            name='speech',
            options={'verbose_name_plural': 'Speeches'},
        ),
        migrations.RenameField(
            model_name='speech',
            old_name='comment',
            new_name='content',
        ),
    ]
