# Generated by Django 4.0.3 on 2022-03-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0033_rename_comment_speech_alter_speech_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='speech_type',
            field=models.CharField(choices=[('True', 'Speech'), ('False', 'Testimonial')], default='False', max_length=50),
        ),
    ]
