# Generated by Django 4.0.3 on 2022-03-08 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0034_speech_speech_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speech',
            name='speech_type',
            field=models.CharField(choices=[('True', 'Quote'), ('False', 'Testimonial')], default='False', max_length=50),
        ),
    ]
