# Generated by Django 4.0.3 on 2022-03-19 22:32

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0040_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=100)),
                ('system_name', models.CharField(max_length=100)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('address', models.CharField(max_length=500)),
                ('telphone', models.CharField(max_length=14)),
                ('email_address', models.EmailField(max_length=50, null=True)),
                ('whatsapp_link', models.CharField(max_length=100, null=True)),
                ('facebook_link', models.CharField(max_length=100, null=True)),
                ('twitter_link', models.CharField(max_length=100, null=True)),
                ('linkedin_link', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
