# Generated by Django 4.0.3 on 2022-03-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0043_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcome',
            name='learning_outcomes',
            field=models.CharField(max_length=256),
        ),
    ]
