# Generated by Django 4.0.3 on 2022-03-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0047_alter_news_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tag',
        ),
        migrations.AddField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(null=True, to='hosannaWebsite.tag'),
        ),
    ]
