# Generated by Django 4.0.3 on 2022-03-20 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0048_remove_news_tag_news_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='tag',
            field=models.ManyToManyField(to='hosannaWebsite.tag'),
        ),
    ]
