# Generated by Django 4.0.3 on 2022-03-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0050_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
