# Generated by Django 4.0.3 on 2022-03-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0052_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='website',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
