# Generated by Django 4.0.3 on 2022-03-26 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0057_subscription_alter_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='assesments',
        ),
        migrations.RemoveField(
            model_name='event',
            name='students',
        ),
    ]
