# Generated by Django 4.0.3 on 2022-03-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0058_remove_event_assesments_remove_event_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='content',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
