# Generated by Django 4.0.3 on 2022-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0059_curriculum_content_curriculum_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='content',
        ),
        migrations.RemoveField(
            model_name='curriculum',
            name='duration',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
