# Generated by Django 4.0.3 on 2022-03-26 12:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0060_remove_curriculum_content_remove_curriculum_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='host',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='short_note',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='skill_level',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='topic',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
