# Generated by Django 4.0.3 on 2022-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0062_course_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='certification',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='popular',
            field=models.IntegerField(choices=[(1, 'Yes'), (0, 'No')], default=0, null=True),
        ),
    ]
