# Generated by Django 4.0.3 on 2022-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0064_pricing_table_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='duration',
            new_name='Test',
        ),
    ]
