# Generated by Django 4.0.3 on 2022-03-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0065_rename_duration_lesson_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='Test',
            new_name='duration',
        ),
    ]
