# Generated by Django 4.0.3 on 2022-03-29 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0067_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosannaWebsite.course'),
        ),
    ]
