# Generated by Django 4.0.3 on 2022-03-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0068_alter_curriculum_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
