# Generated by Django 4.0.3 on 2022-03-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0069_alter_lesson_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermidiate', 'Intermidiate'), ('Advanced', 'Advanced')], max_length=128, null=True),
        ),
    ]
