# Generated by Django 4.0.3 on 2022-03-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0070_alter_course_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
