# Generated by Django 4.0.3 on 2022-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0071_lesson_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='order_number',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='order_number',
            field=models.IntegerField(null=True),
        ),
    ]
