# Generated by Django 4.0.3 on 2022-03-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0072_remove_lesson_order_number_curriculum_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing_table',
            name='url',
        ),
        migrations.AddField(
            model_name='pricing_table',
            name='linked_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hosannaWebsite.course'),
        ),
    ]
