# Generated by Django 4.0.3 on 2022-03-30 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0073_remove_pricing_table_url_pricing_table_linked_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing_table',
            name='linked_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosannaWebsite.course'),
        ),
    ]
