# Generated by Django 4.0.3 on 2022-04-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0074_alter_pricing_table_linked_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('Address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mode_of_payments', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=7)),
                ('payment_status', models.CharField(choices=[(True, 'Paid'), (False, 'Waiting')], max_length=8)),
                ('photograph', models.ImageField(default='anonymous.jpg', upload_to='applications')),
            ],
        ),
    ]
