# Generated by Django 4.0.3 on 2022-04-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0076_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='form',
            field=models.FileField(default='form.pdf', upload_to='forms'),
        ),
    ]
