# Generated by Django 4.0.3 on 2022-04-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0078_rename_address_applications_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='application_form',
            field=models.FilePathField(null=True, path='/media/'),
        ),
    ]
