# Generated by Django 4.0.3 on 2022-04-02 17:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0079_applications_application_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mode_of_payments', models.CharField(choices=[('Cash', 'Cash'), ('Online', 'Online')], max_length=7)),
                ('photograph', models.ImageField(default='anonymous.jpg', upload_to='applications')),
                ('form', models.FileField(default='form.pdf', upload_to='forms')),
                ('application_form', models.FilePathField(null=True, path='hosanna/media/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Applications',
        ),
    ]
