# Generated by Django 4.0.3 on 2022-04-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0088_application_payment_status_alter_application_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='form',
            field=models.FileField(upload_to='forms'),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[(True, 'Paid'), (False, 'Waiting')], default=False, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='photograph',
            field=models.ImageField(upload_to='applications'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Engr', 'Engr'), ('Dr', 'Dr')], default='Mr', max_length=5),
        ),
    ]
