# Generated by Django 4.0.3 on 2022-04-06 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0098_application_payment_status_alter_application_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Miss.', 'Miss'), ('Engr.', 'Engr'), ('Dr.', 'Dr')], default='Mr.', max_length=5),
        ),
    ]
