# Generated by Django 4.0.3 on 2022-04-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hosannaWebsite', '0101_remove_application_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='payment_status',
            field=models.CharField(choices=[(1, 'Paid'), (0, 'Waiting')], default=0, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=7),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr'), ('Mrs.', 'Mrs'), ('Miss.', 'Miss'), ('Engr.', 'Engr'), ('Dr.', 'Dr')], default='Mr.', max_length=5),
        ),
    ]
